# Generated by Django 5.0.6 on 2026-05-16 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("on_hand", models.PositiveIntegerField(default=0)),
                ("reserved", models.PositiveIntegerField(default=0)),
                ("reorder_threshold", models.PositiveIntegerField(default=10)),
                ("version", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_item",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("inbound", "Inbound"),
                            ("reserve", "Reserve"),
                            ("release", "Release"),
                            ("consume", "Consume"),
                            ("adjust", "Adjust"),
                        ],
                        max_length=16,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("reference", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.stockitem",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["stock_item", "-created_at"],
                        name="inventory_s_stock_i_73796c_idx",
                    ),
                    models.Index(
                        fields=["kind", "-created_at"],
                        name="inventory_s_kind_79c19c_idx",
                    ),
                ],
            },
        ),
    ]
